services:

  db:
    image: postgres:15
    restart: unless-stopped

    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: StrongPassword123

  wikijs:
    image: ghcr.io/requarks/wiki:2

    depends_on:
      - db

    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: StrongPassword123
      DB_NAME: wiki

    restart: unless-stopped

    ports:
      - "3000:3000"